# Generated by Django 3.2.6 on 2021-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Language')),
                ('slug', models.SlugField(unique=True)),
                ('flag', models.ImageField(blank=True, upload_to='images/flags')),
                ('summary', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
