# Generated by Django 4.0 on 2022-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20220101_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/flags'),
        ),
        migrations.AlterField(
            model_name='language',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
