# Generated by Django 3.2.6 on 2021-10-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210912_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('date_created', 'date_updated')},
        ),
    ]
