# Generated by Django 4.0 on 2022-01-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PENDING', 'Pending Review'), ('UNAPPROVED', 'Unapproved'), ('FLAGGED', 'Flagged'), ('DELETED', 'Deleted'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=10),
        ),
    ]
