# Generated by Django 4.0 on 2022-01-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_options_remove_blogpost_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBlogPost',
        ),
    ]
