# Generated by Django 4.0 on 2022-01-20 21:08

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluserprofile'),
        ('languages', '0003_alter_language_flag_alter_language_summary'),
        ('categories', '0002_category_created_date_category_deleted_date_and_more'),
        ('blog', '0006_delete_historicalblogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBlogPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created at')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified at')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='slug')),
                ('summary', models.CharField(max_length=255, null=True)),
                ('featured_image', models.TextField(blank=True, max_length=100, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=120, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PENDING', 'Pending Review'), ('UNAPPROVED', 'Unapproved'), ('FLAGGED', 'Flagged'), ('DELETED', 'Deleted'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=10)),
                ('date_scheduled', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Schedule to publish on')),
                ('content', models.TextField(verbose_name='Post content')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='categories.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('language', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='languages.language')),
                ('translated_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'historical blog post',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
