# Generated by Django 3.2.6 on 2021-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('users', '0002_auto_20210912_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='speaks',
            field=models.ManyToManyField(related_name='speakers', to='languages.Language', verbose_name='Languages spoken'),
        ),
    ]
