# Generated by Django 3.2.6 on 2021-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('users', '0003_userprofile_speaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_language',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='languages.language'),
        ),
    ]
