# Generated by Django 4.0 on 2022-01-20 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
