# Generated by Django 4.0 on 2022-01-20 21:08

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluserprofile'),
        ('languages', '0003_alter_language_flag_alter_language_summary'),
        ('categories', '0002_category_created_date_category_deleted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created at')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified at')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('slug', models.SlugField()),
                ('image', models.TextField(blank=True, max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='languages.language')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='categories.category', verbose_name='Parent category')),
                ('translated_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='categories.category', verbose_name='Translated from category')),
            ],
            options={
                'verbose_name': 'historical Category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
